name: nuclei

services:
  nuclei:
    image: projectdiscovery/nuclei:latest
    volumes:
      - ./root/config/nuclei:/root/.config/nuclei
      - ./volumes/data/nuclei:/data
    ports:
      - "172.17.0.1:58001:8080"
    networks:
      - nuclei
    restart: unless-stopped
    command: ["nuclei", "-h"]

networks:
  nuclei:
    external: false